# Use the official MongoDB image as the base image
FROM mongodb/atlas:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Set the entry point to run MongoDB
CMD ["mongod"]